#############################################################################
# Makefile for building: release/ssl-dashboard
# Generated by qmake (2.01a) (Qt 4.8.4) on: dim. oct. 11 18:54:45 2015
# Project:  ssl-dashboard.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ssl-dashboard.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -Ilibs -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/home/abathur/Bureau/open_source/ssl-dashboard/libs -L/usr/lib/i386-linux-gnu -lmongoclient -lboost_thread -lboost_system -lboost_filesystem -lboost_program_options -lhttpServer -lhttpdecoder -ldigestauthsession -lqjson -lsslgen -lssl -lcrypto -ldl -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = server/ClientSocketHandler.cpp \
		server/database.cpp \
		server/HashDigestListener.cpp \
		server/main.cpp \
		server/SslHandler.cpp \
		utils/fileutils.cpp \
		utils/stringutil.cpp moc_database.cpp
OBJECTS       = bin/ClientSocketHandler.o \
		bin/database.o \
		bin/HashDigestListener.o \
		bin/main.o \
		bin/SslHandler.o \
		bin/fileutils.o \
		bin/stringutil.o \
		bin/moc_database.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ssl-dashboard.pro
QMAKE_TARGET  = ssl-dashboard
DESTDIR       = release/
TARGET        = release/ssl-dashboard

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) release/ || $(MKDIR) release/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true 
	rsync -avm --include=*/ --include=*.h --exclude=* /home/abathur/Bureau/open_source/ssl-dashboard// /home/abathur/Bureau/open_source/ssl-dashboard/release

Makefile: ssl-dashboard.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ssl-dashboard.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ssl-dashboard.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/ssl-dashboard1.0.0 || $(MKDIR) bin/ssl-dashboard1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/ssl-dashboard1.0.0/ && $(COPY_FILE) --parents server/ClientSocketHandler.h server/database.h server/HashDigestListener.h server/SslHandler.h utils/fileutils.h utils/stringutil.h bin/ssl-dashboard1.0.0/ && $(COPY_FILE) --parents server/ClientSocketHandler.cpp server/database.cpp server/HashDigestListener.cpp server/main.cpp server/SslHandler.cpp utils/fileutils.cpp utils/stringutil.cpp bin/ssl-dashboard1.0.0/ && (cd `dirname bin/ssl-dashboard1.0.0` && $(TAR) ssl-dashboard1.0.0.tar ssl-dashboard1.0.0 && $(COMPRESS) ssl-dashboard1.0.0.tar) && $(MOVE) `dirname bin/ssl-dashboard1.0.0`/ssl-dashboard1.0.0.tar.gz . && $(DEL_FILE) -r bin/ssl-dashboard1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) -r /home/abathur/Bureau/open_source/ssl-dashboard/release
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_database.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_database.cpp
moc_database.cpp: server/database.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) server/database.h -o moc_database.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

bin/ClientSocketHandler.o: server/ClientSocketHandler.cpp server/ClientSocketHandler.h \
		server/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ClientSocketHandler.o server/ClientSocketHandler.cpp

bin/database.o: server/database.cpp server/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/database.o server/database.cpp

bin/HashDigestListener.o: server/HashDigestListener.cpp server/HashDigestListener.h \
		server/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/HashDigestListener.o server/HashDigestListener.cpp

bin/main.o: server/main.cpp server/SslHandler.h \
		server/ClientSocketHandler.h \
		server/database.h \
		server/HashDigestListener.h \
		utils/fileutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/main.o server/main.cpp

bin/SslHandler.o: server/SslHandler.cpp server/SslHandler.h \
		utils/fileutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/SslHandler.o server/SslHandler.cpp

bin/fileutils.o: utils/fileutils.cpp utils/fileutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/fileutils.o utils/fileutils.cpp

bin/stringutil.o: utils/stringutil.cpp utils/stringutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/stringutil.o utils/stringutil.cpp

bin/moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/moc_database.o moc_database.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

